### ISSUE TITLE
彩色温度文字开关

### ISSUE THREAD

**Issue by aotuitx** [XiaofengdiZhu/openhardwaremonitor#3]
我用了悬浮窗，为啥 有的字体是白色，有的字体是绿色？还是只是我自己这样？

**Comment by aotuitx** [comment]
基本是温度数值是绿色的。。

**Comment by XiaofengdiZhu** [comment]
是特性哦，随温度升高变化
我加个开关吧

**Comment by aotuitx** [comment]
> 是特性哦，随温度升高变化
> 我加个开关吧

悬浮窗的字体颜色能定义设置么？

**Comment by XiaofengdiZhu** [comment]
> > 是特性哦，随温度升高变化
> > 我加个开关吧
> 
> 悬浮窗的字体颜色能定义设置么？

从源码里都能调，但要加到右键菜单里感觉会比较困难……又不想专门整个设置窗口

**Comment by aotuitx** [comment]
> > > 是特性哦，随温度升高变化
> > > 我加个开关吧
> > 
> > 
> > 悬浮窗的字体颜色能定义设置么？
> 
> 从源码里都能调，但要加到右键菜单里感觉会比较困难……又不想专门整个设置窗口

好吧。颜色数值能一至就可以了，全白色还可以。

**Comment by XiaofengdiZhu** [comment]
push了但懒得专门为它release~
